apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bullettrain.fullname" . }}
  labels:
    app: {{ template "bullettrain.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if or (not .Values.postgresql.enabled) (.Values.postgresql.postgresqlUsername) }}
  dbuser: {{ .Values.postgresql.postgresqlUsername | default "" | b64enc | quote }}
  {{ end }}
  {{ if or (not .Values.postgresql.enabled) (.Values.postgresql.postgresqlPassword) }}
  dbpassword: {{ .Values.postgresql.postgresqlPassword | default "" | b64enc | quote }}
  {{ end }}
  {{ if or (not .Values.postgresql.enabled) (.Values.postgresql.postgresqlDatabase) }}
  dbname: {{ .Values.postgresql.postgresqlDatabase | default "" | b64enc | quote }}
  {{ end }}